[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/mental_test/*"
  to = "/mental_test/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
